<H1>Manual Controll of WPS inport functionality</H1>
<ul style="display: block;
    font-size:16px;
    list-style-type: square;
    margin-top: 1em;
    margin-bottom: 1 em;
    margin-left: 0;
    margin-right: 0;
    padding-left: 40px;">
<li><h3>Raw Data</h3></li>
<li><a href="<?php echo $this->getCreateUrl('wps-admin/manual/ftpDaily'); ?>">FTP get daily files</a></li>
<li><a href="<?php echo $this->getCreateUrl('wps-admin/manual/rawQty'); ?>">Update RAW Qty information from file</a></li>
<li><a href="<?php echo $this->getCreateUrl('wps-admin/manual/rawFtpPrice'); ?>">Update RAW Price/Cost information from FTP file</a></li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/uploadMonthlyPrice'); ?>" method="post"  enctype="multipart/form-data">
    Select file to upload:
    <?php echo $this->getBlockHtml('formkey') ?>
    <input type="file" name="monthlyPrice" id="monthlyPrice">
    <input type="submit" value="Upload Price File(.zip)" name="submit">
  </form>
</li>
<li><a href="<?php echo $this->getCreateUrl('wps-admin/manual/rawAPIUpdate'); ?>">Update RAW API table</a></li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/rawAPIPull'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey') ?>
    <label>Quantity</label><input type="text" name="qty" id="qty">
    <label>ItemNum</label><input type="text" name="item" id="item">
    <input type="submit" value="Update API Information" name="submit">
  </form>
</li>

<li><h3>Clean Data</h3></li>
<li><a href="<?php echo $this->getCreateUrl('wps-admin/manual/rawDataUpdate'); ?>">Update RAW Data Table</a></li>
<li><a href="<?php echo $this->getCreateUrl('wps-admin/manual/cleanDataUpdate'); ?>">Update Clean Data Table</a></li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/cleanAttributeUpdate'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey') ?>
    <label>Quantity</label><input type="text" name="qty" id="qty">
    <label>Brand</label><input type="text" name="brand" id=""brand"">
    <input type="submit" value="Update Attributes" name="submit">
  </form>
</li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/cleanFitmentUpdate'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey') ?>
    <label>Quantity</label><input type="text" name="qty" id="qty">
    <label>Brand</label><input type="text" name="brand" id=""brand"">
    <input type="submit" value="Update Fitments" name="submit">
  </form>
</li>
<li><a href="<?php echo $this->getCreateUrl('wps-admin/manual/cleanDataUpdateDescription'); ?>">Update Clean Data Description/Brand/Title</a></li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/cleanBrand'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey') ?>
    <label>Quantity</label><input type="text" name="qty" id="qty">
    <label>Brand</label><input type="text" name="brand" id=""brand"">
    <input type="submit" value="Clean Brand" name="submit">
  </form>
</li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/cleanTitle'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey') ?>
    <label>Quantity</label><input type="text" name="qty" id="qty">
    <label>Brand</label><input type="text" name="brand" id=""brand"">
    <input type="submit" value="Clean Title" name="submit">
  </form>
</li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/cleanDescription'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey') ?>
    <label>Quantity</label><input type="text" name="qty" id="qty">
    <label>Brand</label><input type="text" name="brand" id=""brand"">
    <input type="submit" value="Clean Description" name="submit">
  </form>
</li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/cleanAttribute'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey') ?>
    <label>Quantity</label><input type="text" name="qty" id="qty">
    <input type="submit" value="Clean Attribute" name="submit">
  </form>
</li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/cleanMake'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey') ?>
    <label>Quantity</label><input type="text" name="qty" id="qty">
    <input type="submit" value="Clean Make" name="submit">
  </form>
</li>
<li style="border: solid 1px #000000; padding: 3px;">
  <form action="<?php echo $this->getCreateUrl('wps-admin/manual/cleanModel'); ?>" method="post">
    <?php echo $this->getBlockHtml('formkey') ?>
    <label>Quantity</label><input type="text" name="qty" id="qty">
    <input type="submit" value="Clean Model" name="submit">
  </form>
</li>

<li><h3>Clean Data</h3></li>
<li><a href="<?php echo $this->getCreateUrl('wps-admin/manual/cleanDataTransfer'); ?>">Transfer Cleaned Data</a></li>
</ul>